# Generated by Django 2.2.1 on 2019-05-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, help_text='Please provide valid Email only.', max_length=254, null=True)),
                ('web', models.URLField(blank=True, help_text='Please provide valid URL only.', null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
